// <auto-generated />
using System;
using MeridianEats.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeridianEats.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414080716_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeridianEats.API.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MeridianEats.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "menu_1.png",
                            Name = "Salad"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "menu_2.png",
                            Name = "Rolls"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "menu_3.png",
                            Name = "Deserts"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "menu_4.png",
                            Name = "Sandwich"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "menu_5.png",
                            Name = "Cake"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "menu_6.png",
                            Name = "Pure Veg"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "menu_7.png",
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "menu_8.png",
                            Name = "Noodles"
                        });
                });

            modelBuilder.Entity("MeridianEats.API.Models.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_1.png",
                            IsAvailable = true,
                            Name = "Greek salad",
                            Price = 12m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_2.png",
                            IsAvailable = true,
                            Name = "Veg salad",
                            Price = 18m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_3.png",
                            IsAvailable = true,
                            Name = "Clover Salad",
                            Price = 16m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_4.png",
                            IsAvailable = true,
                            Name = "Chicken Salad",
                            Price = 24m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_5.png",
                            IsAvailable = true,
                            Name = "Lasagna Rolls",
                            Price = 14m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_6.png",
                            IsAvailable = true,
                            Name = "Peri Peri Rolls",
                            Price = 12m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_7.png",
                            IsAvailable = true,
                            Name = "Chicken Rolls",
                            Price = 20m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_8.png",
                            IsAvailable = true,
                            Name = "Veg Rolls",
                            Price = 15m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_9.png",
                            IsAvailable = true,
                            Name = "Ripple Ice Cream",
                            Price = 14m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_10.png",
                            IsAvailable = true,
                            Name = "Fruit Ice Cream",
                            Price = 22m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_11.png",
                            IsAvailable = true,
                            Name = "Jar Ice Cream",
                            Price = 10m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_12.png",
                            IsAvailable = true,
                            Name = "Vanilla Ice Cream",
                            Price = 12m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_13.png",
                            IsAvailable = true,
                            Name = "Chicken Sandwich",
                            Price = 12m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_14.png",
                            IsAvailable = true,
                            Name = "Vegan Sandwich",
                            Price = 18m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_15.png",
                            IsAvailable = true,
                            Name = "Grilled Sandwich",
                            Price = 16m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_16.png",
                            IsAvailable = true,
                            Name = "Bread Sandwich",
                            Price = 24m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_17.png",
                            IsAvailable = true,
                            Name = "Cup Cake",
                            Price = 14m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_18.png",
                            IsAvailable = true,
                            Name = "Vegan Cake",
                            Price = 12m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_19.png",
                            IsAvailable = true,
                            Name = "Butterscotch Cake",
                            Price = 20m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_20.png",
                            IsAvailable = true,
                            Name = "Sliced Cake",
                            Price = 15m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_21.png",
                            IsAvailable = true,
                            Name = "Garlic Mushroom",
                            Price = 14m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_22.png",
                            IsAvailable = true,
                            Name = "Fried Cauliflower",
                            Price = 22m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_23.png",
                            IsAvailable = true,
                            Name = "Mix Veg Pulao",
                            Price = 10m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_24.png",
                            IsAvailable = true,
                            Name = "Rice Zucchini",
                            Price = 12m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 7,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_25.png",
                            IsAvailable = true,
                            Name = "Cheese Pasta",
                            Price = 12m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 7,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_26.png",
                            IsAvailable = true,
                            Name = "Tomato Pasta",
                            Price = 18m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 7,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_27.png",
                            IsAvailable = true,
                            Name = "Creamy Pasta",
                            Price = 16m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 7,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_28.png",
                            IsAvailable = true,
                            Name = "Chicken Pasta",
                            Price = 24m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 8,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_29.png",
                            IsAvailable = true,
                            Name = "Buttter Noodles",
                            Price = 14m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 8,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_30.png",
                            IsAvailable = true,
                            Name = "Veg Noodles",
                            Price = 12m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 8,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_31.png",
                            IsAvailable = true,
                            Name = "Somen Noodles",
                            Price = 20m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 8,
                            Description = "Food provides essential nutrients for overall health and well-being",
                            ImageUrl = "food_32.png",
                            IsAvailable = true,
                            Name = "Cooked Noodles",
                            Price = 15m,
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("MeridianEats.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MeridianEats.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MeridianEats.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MeridianEats.API.Models.CartItem", b =>
                {
                    b.HasOne("MeridianEats.API.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeridianEats.API.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeridianEats.API.Models.FoodItem", b =>
                {
                    b.HasOne("MeridianEats.API.Models.Category", "Category")
                        .WithMany("FoodItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MeridianEats.API.Models.Order", b =>
                {
                    b.HasOne("MeridianEats.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeridianEats.API.Models.OrderItem", b =>
                {
                    b.HasOne("MeridianEats.API.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeridianEats.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MeridianEats.API.Models.Category", b =>
                {
                    b.Navigation("FoodItems");
                });

            modelBuilder.Entity("MeridianEats.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MeridianEats.API.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
